export const publicKey = `
-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGrnvL2PMQjACBESFfbQllsHo7tw
Cv8PENydE/0CEszqV9zkHamlKdU/AnUyUHYfi71NluyT16g2SjMVNkcHqNplUVMn
RmV/cXQnTPtIayJp3z/hyMdwndzvm+6J7aI8OQ8q4b3K/zBEkYMvXH7YcIgwdijL
fMHgL6PZlr2/cJiHAgMBAAE=
-----END PUBLIC KEY-----`;
